import { GetServerSideProps } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import React, { FormEvent, useEffect, useRef, useState } from 'react';

import SearchHeader from '../components/SearchHeader';
import SearchResult from '../components/SearchResult';
import { DUMMY_DATA } from '../Response';

const Search = ({ results }: any) => {
  const router = useRouter();
  const routerQuery = router.query.term;

  return (
    <div>
      <Head>
        <title>{routerQuery} — Google Search</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      {/* Header */}
      <SearchHeader />

      {/* Search Result */}
      <SearchResult results={results} />
    </div>
  );
};

export default Search;

export const getServerSideProps: GetServerSideProps = async (context) => {
  const useDummyData = true;

  const startIndex = context.query.start || '0';

  const data = useDummyData
    ? DUMMY_DATA
    : await fetch(
        `https://www.googleapis.com/customsearch/v1?key=${process.env.NEXT_PUBLIC_API_KEY}&cx=${process.env.NEXT_PUBLIC_CONTEXT_KEY}&q=${context.query.term}&start=${startIndex}`
      ).then((response) => response.json());

  // After the SERVERSIDE render... Pass the result to the client
  return {
    props: {
      results: data,
    },
  };
};
