import { MicrophoneIcon, SearchIcon, ViewGridIcon, XIcon } from '@heroicons/react/outline';
import { CogIcon } from '@heroicons/react/solid';
import Head from 'next/head';
import Image from 'next/image';
import { useRouter } from 'next/router';
import React, { FormEvent, useRef } from 'react';
import Avatar from '../components/Avatar';

const Search = () => {
  const router = useRouter();
  const searchInputRef = useRef<HTMLInputElement>(null);

  const searchHandler = (e: FormEvent) => {
    e.preventDefault();

    const query = searchInputRef.current?.value;

    if (!query) return;

    router.push(`/search?term=${query}`);
  };

  return (
    <div>
      <Head>
        <title>Search</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      {/* Header */}
      <header className='flex gap-10 items-center w-full px-6 py-7 border-b border-gray-200 sticky top-0 bg-white'>
        <div
          className='relative w-[120px] h-[40px] cursor-pointer'
          onClick={() => router.push('/')}
        >
          <Image
            src={'http://assets.stickpng.com/images/580b57fcd9996e24bc43c51f.png'}
            layout='fill'
            objectFit='contain'
            alt='google logo'
          />
        </div>

        <form className='flex-grow flex items-center w-full ring-1 ring-gray-200 max-w-md pr-3 rounded-full focus-within:shadow-lg'>
          <input
            type='text'
            placeholder='hello'
            ref={searchInputRef}
            className='outline-none w-full py-2 pl-4 bg-transparent'
          />

          <div className='flex gap-3'>
            <XIcon
              className='w-5 h-5 cursor-pointer transition-all duration-100 ease-out hover:scale-125'
              onClick={() => (searchInputRef.current!.value = '')}
            />

            <div className='hidden sm:inline-flex gap-3'>
              <div className='border-r border-gray-200' />
              <MicrophoneIcon className='w-5 h-5 cursor-pointer transition-all duration-100 ease-out hover:scale-125' />
              <SearchIcon className='w-5 h-5 cursor-pointer transition-all duration-100 ease-out hover:scale-125' />
            </div>
          </div>

          <button onClick={searchHandler} hidden>
            Submit
          </button>
        </form>

        <div className='ml-auto flex items-center'>
          <div className='w-11 h-11 flex items-center justify-center cursor-pointer rounded-full hover:bg-gray-200'>
            <CogIcon className='w-6 h-6' />
          </div>

          <div className='w-11 h-11 flex items-center justify-center cursor-pointer rounded-full hover:bg-gray-200'>
            <ViewGridIcon className='h-6 w-6' />
          </div>

          {/* Avatar */}
          <div>
            <Avatar url='/jaber 2.jpg' />
          </div>
        </div>
      </header>

      {/* Search Result */}
    </div>
  );
};

export default Search;
